<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AuraSpace | Futuristic Luxury Showroom</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <!-- Cinematic Entry Loader -->
    <div id="loader" class="loader-overlay">
        <div class="loader-spinner"></div>
    </div>

    <!-- Navigation -->
    <?php include 'components/navbar.php'; ?>

    <!-- Background Parallax Setup -->
    <div class="parallax-bg">
        <div class="floating-obj obj-1 parallax-obj" data-speed="15"></div>
        <div class="floating-obj obj-2 parallax-obj" data-speed="-10"></div>
        <div class="floating-obj obj-3 parallax-obj" data-speed="20"></div>
        <!-- Abstract elements -->
        <div style="position:absolute; top:40%; left:10%; width:100px; height:100px; border-radius:50%; border:1px solid rgba(255,255,255,0.1); animation: float 10s infinite;" class="parallax-obj" data-speed="-15"></div>


    <!-- Original Hero Section -->
    <section id="home" class="hero">
        <div class="hero-content parallax-obj" data-speed="-5">
            <img src="assets/images/auraspace_logo.png" alt="AuraSpace Logo" style="width: 120px; margin-bottom: 20px; filter: drop-shadow(0 0 15px rgba(0, 243, 255, 0.5)); mix-blend-mode: screen;">
            <h1 class="hero-title">Discover The<br><span class="text-gradient">AuraSpace</span> Universe</h1>
            <p class="hero-desc">Immerse yourself in a cinematic digital showroom. Experience the world's most premium men's fragrances floating in a dimension of unparalleled luxury and glassmorphic elegance.</p>
            <a href="orbit.php" class="btn-primary" style="display: inline-block; text-decoration: none;">Explore Collections</a>
        </div>
        <div class="hero-visual parallax-obj" data-speed="10">
            <!-- Glow Rings -->
            <div class="glow-ring"></div>
            <div class="glow-ring"></div>
            
            <!-- Orbit Profiles Container -->
            <div id="orbit-profiles-container" style="position:absolute; top:0; left:0; width:100%; height:100%; pointer-events:none;"></div>
            
            <!-- Giant floating perfume bottle generated by AI -->
            <img src="assets/images/hero.png" alt="Premium Perfume" class="hero-bottle" style="position:relative; z-index:5;">
        </div>
    </section>



    <!-- Footer -->
    <?php include 'components/footer.php'; ?>

    <script src="script.js"></script>
</body>
</html>
